services:
  testdb:
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'exit' | sqlplus -S system/testpassword@//localhost:1521/XE || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      testdb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "80:3000"
    depends_on:
      - backend