services:
  testdb:
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "1522:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'exit' | sqlplus -S system/testpassword@//localhost:1521/XE || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - DB_URL=jdbc:oracle:thin:@testdb:1521:XE
    depends_on:
      testdb:
        condition: service_healthy
    command: ["mvn", "test"]
