DELETE FROM CHAT_MESSAGES;
DELETE FROM CHAT_USERS;
DELETE FROM COMMENTS;
DELETE FROM COMMENT_LIKES;
DELETE FROM CONVERSATIONS;
DELETE FROM CONVERSATION_MEMBERS;
DELETE FROM FRIENDSHIPS;
DELETE FROM FRIENDSHIP_REQUESTS;
DELETE FROM MESSAGE_LIKES;
DELETE FROM POSTS;
DELETE FROM POST_LIKES;

COMMIT;